version: "3.8"

services:
  pg_database:
    image: postgres
    container_name: pgdatabase
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydatabase
    volumes:
      - ./pgdata:/data/postgres
